algoritmo "maior número inteiro"
// Função : Informar o maior entre dois números inteiros
// Autor : Caio Marcelo da Silva de Jesus
// Data : 25/03/2020
// Seção de Declarações 
var
    num1, num2: inteiro
inicio
// Seção de Comandos 
   leia (num1)
   leia (num2)
   se (num1 > num2) entao
   escreva ("O maior número inteiro é: ",num1)
   senao
   escreva ("O maior número inteiro é: ", num2)
   fimse
fimalgoritmo

