algoritmo "número inteiro"
// Função : Informar o maior entre dois números inteiros
// Autor : Caio Marcelo da Silva de Jesus
// Data : 25/03/2020
// Seção de Declarações 
var
    num: inteiro
inicio
// Seção de Comandos 
   leia (num)
   se (num = 0) entao
   escreva ("O número é igual a zero")
   senao
   se (num > 0) entao
   escreva ("O número é positivo")
   senao
   escreva ("O número é negativo")
   fimse
   fimse
fimalgoritmo

