algoritmo "calcula media"
// Função :
// Autor :
// Data : 02/03/2020
// Seção de Declarações 
var
   Nota1, Nota2, MediaFinal: real
//   Nota2: real
//   MediaFinal: real

inicio
// Entradas
   escreva("Digite a Nota 1 (0-10): ")
   leia(Nota1)
   escreva("Digite a Nota 2 (0-10): ")
   leia(Nota2)
   
//Processamento
   MediaFinal <- (Nota1 + Nota2) / 2
   
//Saida
   escreval("A Média Final calculada foi de ", MediaFinal)
fimalgoritmo
